### PR TITLE
Fix log level.  afterEach callback before save to schema_version

### PR DESCRIPTION
**Pull request by e11it**
- Fix verbose mode(log level)
- Apply afterEach callback before save to schema_version

### CODE REVIEW

**Comment by secwall** [comment]
There are actually 2 issues with this PR
1. This is not a "fix" of log level. It is a breaking of verbose log levels entirely
2. afterEach callback should not be applied before schema_version save (and this is a breaking change also)

So I'm closing this.

**Comment by e11it** [comment]
Ok.
About verbose. Ah =) I understand.... It better to add in help text `-vvv for more` =)

About second point.
Table `schema_version` created before any callbacks with user connected to.
We use `set role` in callbacks to change role(with default privileges). And there is no way to reset role back. So insert to `schema_version` fall with permission denied.
We found to call callbacks before writing information about applied step more useful.
Anyway thanks for pgmigrate =)

**Comment by secwall** [comment]
> We use set role in callbacks to change role(with default privileges)

There is a session setup option:
```
root@79da60783286:/test# pgmigrate -n -c 'dbname=postgres user=postgres password=test host=localhost' -s 'set role testrole' -vvv -t latest migrate
...
root@79da60783286:/test# pgmigrate -c 'dbname=postgres user=postgres password=test host=localhost' -s 'set role testrole' -vvv -t latest info
...
{
    "1": {
        "version": 1,
        "description": "test",
        "type": "auto",
        "installed_by": "testrole",
        "installed_on": "2021-09-07 07:13:41",
        "transactional": true
    }
}
```
So it seems that doing this in callbacks is not necessary.

**Comment by e11it** [comment]
We have admin role with default privileges(input_admin in example) for each scheme and all object in scheme created from this user. Sometimes we grant this role to another users...
For security reasons it's better when `schema_version` created with super user and schema admin role not able to modify this information.

As example:
```
dwh=# \dts input.*
                List of relations
 Schema |      Name      |   Type   |    Owner
--------+----------------+----------+-------------
 input  | kafka          | table    | input_admin
 input  | kafka_id_seq   | sequence | input_admin
 input  | schema_version | table    | postgres
 ```

**Pull request closed without merging**
