### PR TITLE
Add support for `Postgresql schema` parameter

### PR DESCRIPTION
**Pull request by grihabor**
It's a continuation of thread https://github.com/yandex/pgmigrate/pull/14. I've accidentally deleted my branch and the pr was automatically closed.

### CODE REVIEW

**Comment by grihabor** [comment]
@secwall How to fix the pipeline? 
```
Executing: /tmp/apt-key-gpghome.DzBqAh4k6Z/gpg.1.sh --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
gpg: keyserver receive failed: Cannot assign requested address
```

**Comment by grihabor** [comment]
@secwall Could you give me some feedback on the feature? Are you ok to add it or it is useless to argue?

**Comment by grihabor** [comment]
@secwall ? :cry:

**Comment by secwall** [comment]
There is still the same issue as in #14. Having 2 schemas with 2 different versions in one database is going to be a lot more painful than always using `public` in every database.

**Comment by grihabor** [comment]
But there is a trouble if your database maintainers have only given you an access to a specific schema. The problem takes place if you don't want to create and maintain a separate database for a project just because pgmigrate does not support different schema than `public`

**Comment by eirnym** [comment]
@grihabor I've sent you a PR to fix conflicts

**Comment by eirnym** [comment]
@secwall Users not always have an application attached to the schema `public`. This patch doesn't add any additional complexity other than ability to connect to an arbitrary schema. Value `public` is a good default, used in most cases, but sometimes you need to use other.

**Comment by eirnym** [comment]
@grihabor Could you do reformatting?

**Comment by secwall** [comment]
Hello. I've implemented schema and schema restriction support (it does not cover all cases, for example relation drop and nontransactional migrations could not be checked, but could save us from most problems with several schemas in one database) in 1aa3687.
So I'm closing this.

**Pull request closed without merging**
