### PR TITLE
Adding DB connection information to documentation

### PR DESCRIPTION
**Pull request by i8enn**
Hello! I added support for configuring the connection string via environment variables. Priority is still given to the config file and the `--conn` option.

The solution is not the most elegant, but it works.

*P.S. Unfortunately, I did not cover this with tests, since you are using a rather specific testing mechanism (I have not worked with it before)*

### CODE REVIEW

**Comment by secwall** [comment]
Hi. You could use [environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) with connection value set to empty string `''`.

**Comment by i8enn** [comment]
@secwall, thank you for such a quick response!

> Hi. You could use environment variables with connection value set to empty string ''

You mean an environment variable like `DATABASE_URL=''` won't work?

**Comment by secwall** [comment]
It is not necessary to add new environment variable. You could use env variables from libpq if configuration via environment is required.

**Comment by i8enn** [comment]
> It is not necessary to add new environment variable. You could use env variables from libpq if configuration via environment is required.

@secwall Oh, thank you! Unfortunately, this is not entirely obvious. Can I delete the code I added and just replace the connection description through my variable with `libpq` in docs?

Like:
- Using `libpq` environment variables:

    ```bash
    PGUSER=postgres PGPASSWORD=postgres PGHOST=postgres PGPORT=5432 pgmigrate -t 1 info
    ```

---------------

*P.S.: I removed the redundant environment variable and left only the documentation updated. If you find it necessary to accept this PR, I will be grateful (if not, just close it).*

**Comment by secwall** [comment]
I've added [example configuration description](https://github.com/yandex/pgmigrate/blob/master/doc/tutorial.md#configuration) in 3bd4963. So now it should be obvious how to pass connection configuration via environment.

**Comment by i8enn** [comment]
@secwall, thanks! It has become much clearer now. Then my PR is unnecessary - I closing this PR.

Thanks again for such a quick and well-coordinated work!

**Pull request closed without merging**
